name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check if release needed
        id: check
        run: |
          # Check if the last commit is a merge commit or has meaningful changes
          if git log -1 --pretty=format:"%s" | grep -E "\[skip release\]|\[no release\]"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate new tag
        id: tag
        if: steps.check.outputs.skip == 'false'
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          DRY_RUN: false
          # Conventional commits:
          # fix: -> patch version
          # feat: -> minor version  
          # BREAKING -> major version

      - name: Run GoReleaser
        if: steps.check.outputs.skip == 'false'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 